name: Pull Check

on:
  pull_request:

jobs:

  run-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2.1.2
      with:
        node-version: 14.11

    - name: Checkout repo ðŸ‘€
      uses: actions/checkout@v2.3.3

    - name: Install Dependencies
      run: npm install

    - name: ðŸ” Write swr-lab login
      run: echo '${{ secrets.KEYS__SWR_VOX_BI }}' > ./keys/swr-lab.json
    
    - name: ðŸ” Write stationConfig
      run: echo '${{ secrets.KEYS__STATION_CONFIG }}' > ./stationConfig.js

    - name: Run index
      run: npm run test
